apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: reloader
  annotations:
    reloader.stakater.com/auto: "true"
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            server_name localhost;

            location / {
              return 200 'Hello from NGINX!';
              add_header Content-Type text/plain;
            }
        }
    }

